# Generated by Django 3.1.2 on 2020-10-16 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharefile',
            name='receiver_id',
            field=models.EmailField(default='test', max_length=100),
        ),
    ]
