# Generated by Django 3.1.2 on 2020-10-16 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201016_0727'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharefile',
            name='file_path',
            field=models.CharField(default='test', max_length=500),
        ),
        migrations.AlterField(
            model_name='sharefile',
            name='receiver_id',
            field=models.EmailField(default='test@test.com', max_length=100),
        ),
    ]
