# Generated by Django 3.1.1 on 2020-10-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201016_0738'),
    ]

    operations = [
        migrations.CreateModel(
            name='urlMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.CharField(max_length=500)),
                ('short_token', models.CharField(max_length=100)),
            ],
        ),
    ]
