# Generated by Django 3.1.1 on 2020-11-06 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_urlmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlmapping',
            name='opened',
            field=models.BooleanField(default=False),
        ),
    ]
