# Generated by Django 3.1.3 on 2020-11-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_sharefile_doctor_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='passwordResetRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='test@test.com', max_length=100)),
                ('token', models.CharField(default='', max_length=250)),
                ('requestAcceptedAt', models.DateTimeField(auto_now_add=True)),
                ('requestUsed', models.BooleanField(default=False)),
            ],
        ),
    ]
