# Generated by Django 3.1.3 on 2020-11-14 17:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_passwordresetrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='requestAcceptedAt',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
